export const data = {
  skills: [
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
    {
      area: "",
      label: "",
      iconName: "",
      duration: "",
      usage: "",
      description: "",
    },
  ],
  work: [
    {
      imageName: "",
      label: "",
      description: "",
      tags: [
        {
          label: "",
          skillArea: "",
          color: "",
        },
        {
          label: "",
          skillArea: "",
          color: "",
        },
        {
          label: "",
          skillArea: "",
          color: "",
        },
      ],
      liveUrl: "",
      codeUrl: "",
    },
    {
      imageName: "",
      label: "",
      description: "",
      tags: [
        {
          label: "",
          skillArea: "",
          color: "",
        },
        {
          label: "",
          skillArea: "",
          color: "",
        },
        {
          label: "",
          skillArea: "",
          color: "",
        },
      ],
      liveUrl: "",
      codeUrl: "",
    },
  ],
};
